services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_PROJECT_NAME: ${VITE_PROJECT_NAME:-Drishtiksha}
                VITE_PROJECT_DESC: ${VITE_PROJECT_DESC:-Deepfake Detection}
                VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:3000}
                NODE_ENV: ${NODE_ENV:-production}
        container_name: vidvigilante-frontend
        ports:
            - "${FRONTEND_PORT:-80}:80"
        environment:
            - NODE_ENV=${NODE_ENV:-production}
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - vidvigilante-network

networks:
    vidvigilante-network:
        external: true
        name: backend_vidvigilante-network
