# /home/dell-pc-03/Deepfake/deepfake-detection/Raj/configs/config_lstm.yaml

# -- Project Configuration --
project_name: "DeepfakeDetection_SigLIP_LSTM"
working_dir: "/home/dell-pc-03/Deepfake/deepfake-detection/Raj/LSTM_video"

# -- Data Configuration --
real_data_path: "/home/dell-pc-03/Deepfake/deepfake-detection/data/CelebDF-V2/Celeb-real"
fake_data_path: "/home/dell-pc-03/Deepfake/deepfake-detection/data/CelebDF-V2/Celeb-synthesis"
validation_split: 0.2
num_frames_per_video: 30 # Using more frames for better temporal context

# -- Model Configuration --
base_model_path: "models/siglip-base" # Using the local base model
num_classes: 2
# -- NEW: LSTM Hyperparameters --
lstm_hidden_size: 512
lstm_num_layers: 2

# -- Training Configuration --
device: "cuda"
num_epochs: 25
batch_size: 4 # Keep low for high frame count
learning_rate: 0.00001 # Often good to use a slightly lower LR for fine-tuning complex heads
optimizer: "AdamW"
patience: 5

# -- NEW: Output Configuration for LSTM model --
best_model_save_path: "models/siglip_lstm_deepfake_detector_best.pth" 
checkpoint_path: "checkpoints/lstm_latest_checkpoint.pth"
output_dir: "outputs_lstm"